### ISSUE TITLE
epic: `cortex model update`

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1186] opened 2024-09-11 05:16 UTC
## Goal 

- Cortex can "update" a model by re-pulling from source
- `cortex model update llama3.1`

## Key Decisions

- I'm personally not sure if this is the correct UX

**Comment by gabrielle-ong** [comment] 2024-11-28 04:16
Closing, duplicate of #1060

**Closed as completed by gabrielle-ong** 2024-11-28 04:16 UTC
Labels: wontfix
